{{- if .Values.selenoid.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: selenoid-config
  labels:
    app: selenoid
data:
  browsers.json: |
    {
      "chrome": {
        "default": "131.0",
        "versions": {
          "131.0": {
            "image": "{{ .Values.selenoid.browsers.chrome.image }}",
            "port": "{{ .Values.selenoid.browsers.chrome.port }}",
            "path": "/"
          }
        }
      },
      "firefox": {
        "default": "133.0",
        "versions": {
          "133.0": {
            "image": "{{ .Values.selenoid.browsers.firefox.image }}",
            "port": "{{ .Values.selenoid.browsers.firefox.port }}",
            "path": "/wd/hub"
          }
        }
      }
    }
{{- end }}
