from typing import Protocol

from src.main.api.models.base_model import BaseModel


class CrudEndpointInterface(Protocol):
    def post(self, model: BaseModel) -> BaseModel: ...
    def get(self, id: int) -> BaseModel: ...
    def update(self, id: int, model: BaseModel) -> BaseModel: ...
    def delete(self, id: int) -> bool: ...
